version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./new_backend
    ports:
      - "4000:4000"
#  nginx:
#    build: ./nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - frontend
#      - backend