version: '3'
services:
  frontend:
    image: clock-front
    command: "npm start"
    ports:
      - "3000:3000"
  backend:
    image: clock-back
    command: "npm start"
    ports:
      - "4000:4000"
    env_file: .env