const OBS_OUTPUT_EVENTS = {
  OBS_WEBSOCKET_OUTPUT_STARTED: "start",
  OBS_WEBSOCKET_OUTPUT_STOPPED: "stop",
  OBS_WEBSOCKET_OUTPUT_PAUSED: "pause",
  OBS_WEBSOCKET_OUTPUT_RESUMED: "resume"
};

export { OBS_OUTPUT_EVENTS };
